routes/web.php
.<?php

use FindService\Categoria;
use FindService\Servicio;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//Rutas de Sesión
Route::get('/','PagesController@inicio')->name('home');
Route::get('login','PagesController@login')->name('login');
Route::get('signup','PagesController@signup')->name('signup');
Route::post('login2','Auth\LoginController@login2')->name('login2');
Auth::routes();
Route::post('logout','Auth\LoginController@logout')->name('logout');
Route::get('perfil/{id}','PagesController@verPerfil')->name('perfil');
Route::post('recuperarContrasena','Auth\ForgotPasswordController@recuperarContrasena')->name('recuperarContra');
Route::get('recuperarPassword', function() {
    return view('auth/recuperarContra');
})->name('password.request');

//Rutas de Inicio de Sesión con Google o Facebook
Route::get('auth/{provider}', 'Auth\RegisterController@redirectToProvider');
Route::get('auth/{provider}/callback', 'Auth\RegisterController@handleProviderCallback');

//Rutas de Servicios
Route::get('Servicio', 'ServicioController@show')->name('showService');
Route::get('signService', 'ServicioController@create')->name('sservice');
Route::get('service', 'ServicioController@servicio')->name('service');
Route::get('catSalud','ServicioController@categoriaSalud')->name('cat_salud');

//Rutas del blog
Route::get('blog', 'PagesController@blog')->name('blog');
//Route::controller('post', 'PostController');
//Route::controller('comments', 'CommentController');

Route::get('categoria/{id}', function($idCategoria){
  $cat = Categoria::findOrFail($idCategoria);
  $servicios = Servicio::where('idCategoria',$idCategoria)->get();
  return view('categoria')->with('cat',$cat)->with('servicios',$servicios);
})->name('categoria');

Route::resource('prueba','PagesController');
Route::resource('servicio','ServicioController');

resources/views/Blog.blade.php
@extends ('plantilla')

@section ('contenido')
  <!-- Contenido principal de la pagina -->
  <br><br>
  <div class="container">
    <div class="row">
      <section class="col s8 offset-s2 center">
        <!-- -->
        <ul class="collapsible">
          <li>
            <div class="collapsible-header">
              <i class="material-icons">send</i>Agregar Post
            </div>
            <div class="collapsible-body">
              <div class="modal-content">
                <div class="row">
                  <form class="col s12">
                    <div class="row">
                      <div class="input-field col s12">
                        <strong style="font-weight: bold" class="blue-text text-darken-4">Título: <strong>
                            <input id="input_text" type="text" data-length="50">
                      </div>
                    </div>
                    <div class="row">
                      <div class="input-field col s12">
                        <strong style="font-weight: bold" class="blue-text text-darken-4">Comentario: <strong>
                            <textarea id="textarea2" class="materialize-textarea" data-length="200"></textarea>
                      </div>
                    </div>
                    <div class="row">
                        <form action="#">
                            <div class="file-field input-field">
                              <div class="btn">
                                <span>File</span>
                                <input type="file">
                              </div>
                              <div class="file-path-wrapper">
                                <input class="file-path validate" type="text">
                              </div>
                            </div>
                          </form>
                    </div>
                  </form>
                </div>
                <div>
                </div>

                <div class="row">
                  <div class="col s12">
                    <button type="button" class="btn blue darken-4" name="button">Enviar Comentario</button>
                  </div>
                </div>
              </div>
            </div>
          </li>
        </ul>
        <!--Card de visualizacion-->
        <div class="card">
          <div class="card-image">
            <img class="activator" src="https://www.estrategiaynegocios.net/csp/mediapool/sites/dt.common.streams.StreamServer.cls?STREAMOID=yoKSb9IAT3noUva4Uy5vVM$daE2N3K4ZzOUsqbU5sYtNU7N1fD39KajhHfIQXYMg6FB40xiOfUoExWL3M40tfzssyZqpeG_J0TFo7ZhRaDiHC9oxmioMlYVJD0A$3RbIiibgT65kY_CSDiCiUzvHvODrHApbd6ry6YGl5GGOZrs-&CONTENTTYPE=image/jpeg">
          </div>
          <div class="card-content blue-text text-darken-4">
            <strong style="font-weight: bold" class="card-title">Pollo Campero</strong>
            <p>Aqui va el comentario</p>
          </div>
        </div>
      </section>
    </div>
  </div>
  <!--  -->
  @endsection
  @section('scripts')
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-rc.2/js/materialize.min.js"></script>
  <script>
    document.addEventListener('DOMContentLoaded', function () {
      var elems = document.querySelectorAll('.sidenav');
      var instances = M.Sidenav.init(elems);
    });
  </script>
  <script>
    document.addEventListener('DOMContentLoaded', function () {
      var elems = document.querySelectorAll('.parallax');
      var instances = M.Parallax.init(elems);
    });
  </script>
  <script>
    document.addEventListener('DOMContentLoaded', function () {
      var elems = document.querySelectorAll('.carousel');
      var instances = M.Carousel.init(elems);
    });
  </script>
  <script>
    var instance = M.Carousel.init({
      fullWidth: true,
      indicators: true
    });
  </script>
  <script>
  document.addEventListener('DOMContentLoaded', function () {
    M.AutoInit();
  });
</script>
@endsection

resources/views/CategoriaSalud.blade.php
@extends ('plantilla')

@section ('busqueda')

    <!-- Contenido principal de la pagina -->
    <br><br>
    <div class="container">
      <div class="row">
          <section class="col s12 center">
              <h1 class = "z-depth-5 green section white-text">SALUD</h1>
            </section>
        <section class="col s8 offset-s2 center">
          <form>
            <div class="input-field">
              <input id="search_bar" type="search" required>
              <label class="" for="search_bar"><i class="material-icons left">search</i>Busca servicios como hospitales, restaurantes, tiendas, etc...</label>
              <i class="material-icons">close</i>
            </div>
          </form>
        </section>
      </div>
    </div>

    <div class="container">
      <div class="row">
          <div class="col s6 l4">
              <div class="card">
                  <div class="card-image">
                    <img src="imagenes\pruebaServicio\logo.png">
                    <a href="{{ route('servicio.show',3) }}" class="btn-floating pulse halfway-fab waves-effect waves-light green"><i class="material-icons">subdirectory_arrow_right</i></a>
                  </div>
                  <div class="card-content">
                      <strong style="font-weight: bold" class="blue-text text-darken-4">Hospital Privado Quetzaltenango S.A.<strong>
                  </div>
                </div>
          </div>
      </div>
    </div>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-rc.2/js/materialize.min.js"></script>
    <script>
      document.addEventListener('DOMContentLoaded', function() {
        var elems = document.querySelectorAll('.sidenav');
        var instances = M.Sidenav.init(elems);
      });
    </script>
    <script>
    document.addEventListener('DOMContentLoaded', function() {
      var elems = document.querySelectorAll('.parallax');
      var instances = M.Parallax.init(elems);
    });
    </script>
    <script>
    document.addEventListener('DOMContentLoaded', function() {
      var elems = document.querySelectorAll('.carousel');
      var instances = M.Carousel.init(elems);
    });
    </script>
    <script>
      var instance = M.Carousel.init({
        fullWidth: true,
        indicators: true
      });
    </script>
@endsection

resources/views/categoria.blade.php
@extends ('plantilla')

@section ('busqueda')

    <!-- Contenido principal de la pagina -->
    <br><br>
    <div class="container">
      <div class="row">
        <section class="col s12 center">
          <h1 class = "section white-text" style="background: #f12d2d;">{{ $cat->nombre }}</h1>
        </section>
        <section class="col s8 offset-s2 center">
          <form>
            <div class="input-field">
              <input id="search_bar" type="search" required>
              <label class="" for="search_bar"><i class="material-icons left">search</i>Busca servicios como hospitales, restaurantes, tiendas, etc...</label>
              <i class="material-icons">close</i>
            </div>
          </form>
        </section>
      </div>
    </div>

    <div class="container">
      <div class="row">
        @foreach ($servicios as $service)
          <div class="col s6 m4 l3">
            <div class="card">
              <div class="card-image">
                <!--img src="imagenes\pruebaServicio\logo.png"-->
                <a href="{{ route('servicio.show',$service->idservicio) }}" class="btn-floating pulse halfway-fab waves-effect waves-light" style="background: #f12d2d;"><i class="material-icons">subdirectory_arrow_right</i></a>
              </div>
              <div class="card-content">
                <strong style="font-weight: bold" class="blue-text text-darken-4">{{ $service->nombre }}<strong>
                </div>
              </div>
            </div>
        @endforeach
      </div>
    </div>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-rc.2/js/materialize.min.js"></script>
    <script>
      document.addEventListener('DOMContentLoaded', function() {
        var elems = document.querySelectorAll('.sidenav');
        var instances = M.Sidenav.init(elems);
      });
    </script>
    <script>
    document.addEventListener('DOMContentLoaded', function() {
      var elems = document.querySelectorAll('.parallax');
      var instances = M.Parallax.init(elems);
    });
    </script>
    <script>
    document.addEventListener('DOMContentLoaded', function() {
      var elems = document.querySelectorAll('.carousel');
      var instances = M.Carousel.init(elems);
    });
    </script>
@endsection

resources/views/comida.blade.php
@extends ('plantilla')

@section ('busqueda')
  <div>
    <hr>
    <div class="parallax-container">
        <div class="parallax"><img class="responsive-image" src="imagenes/Comida.jpg"></div>
        <br><br><br><br><br><br><br>
        <div id="search_div_comida" class="row container">
          <section class="col s12 center white-text">
            <h4>
              En la categoría comida puedes encontrar Restaurantes, Cafeterías, Comedores y más!
            </h4>
          </section>
          <section class="col s8 offset-s2 center">
            <form>
              <div class="input-field">
                <input id="search_bar" type="search" required>
                <label class="" id="label_search" for="search_bar"><i class="material-icons left">search</i>Buscar servicio</label>
                <i class="material-icons">close</i>
              </div>
            </form>
          </section>
        </div>
    </div>
    <hr>
  </div>
@endsection

@section('contenido')
<div class="row container">
  <div class="col s12 l10 offset-l1">
    <div class="slider">
      <ul class="slides">
        <li>
          <img class="green" src="" alt="">
          <div class="caption center-align">
            <h3>Salud</h3>
            <h5 class="light">En esta categoría encontrarás:
              Doctores, Clínicas, Hospitales, Farmacias y más</h5>
            <a class="btn waves-effect white green-text" href="{{ route('cat_salud') }}">Ir a Categoría Salud</a>
          </div>
        </li>
        <li>
          <img src="" alt="" class="orange accent-4">
          <div class="caption left-align">
            <h3>Comida</h3>
            <h5 class="light">En esta categoría encontrarás:
              Restaurantes, Cafeterías, Comedores y más</h5>
            <a class="btn waves-effect white orange-text text-accent-4" href="{{ route('cat_comida') }}">Ir a Categoría Comida</a>
          </div>
        </li>
        <li>
          <img src="" alt="" class="purple">
          <div class="caption right-align">
            <h3>Comercio</h3>
            <h5 class="light">En esta categoría encontrarás:
              Tiendas, Centros Comerciales, Ferreterías, Librerías y más</h5>
            <a class="btn waves-effect white purple-text" href="comercio.html">Ir a Categoría Comercio</a>
          </div>
        </li>
        <li>
          <img src="" alt="" class="red">
          <div class="caption left-align">
            <h3>Profesional</h3>
            <h5 class="light">En esta categoría encontrarás:
              Abogados, Ingenieros, Contadores, Administradores y más</h5>
            <a class="btn waves-effect white red-text" href="profesional.html">Ir a Categoría Profesional</a>
          </div>
        </li>
        <li>
          <img src="" alt="" class="amber">
          <div class="caption right-align">
            <h3>Ocio</h3>
            <h5 class="light">En esta categoría encontrarás:
              Centros de convivencia y diversos lugares para divertirte</h5>
            <a class="btn waves-effect white amber-text" href="ocio.html">Ir a Categoría Ocio</a>
          </div>
        </li>
      </ul>
    </div>
  </div>
</div>
@endsection

resources/views/inicio.blade.php
@extends ('plantilla')

@section ('busqueda')
<div>
  <br><br><br><hr>
  <div class="parallax-container">
      <div class="parallax"><img src="imagenes/servicios.png"></div>
      <br><br><br><br><br><br><br>
      <div id="search_div_inicio" class="row container">
        <section class="col s12 center white-text">
          <h4>
            En FindService puedes encontrar lo que quieras!
          </h4>
        </section>
        <section class="col s8 offset-s2 center">
          {!! Form::open(array('url'=>'/','method'=>'GET','autocomplete'=>'off','role'=>'search')) !!}
            <div class="input-field">
              <input name="searchText" class="" id="search_bar" type="search">
              <label class="" id="label_search" for="search_bar"><i class="material-icons left">search</i>Busca servicios como hospitales, restaurantes, tiendas, etc...</label>
              <i class="material-icons">close</i>
              <button type="submit" class="btn">Buscar</button>
            </div>
          {{form::close()}}
        </section>
      </div>
  </div>
  <hr>
</div>
@endsection

@section('contenido')
<div class="row container">
  @foreach ($servicio as $service)

    <div class="col s6 m4 l3">
      <div class="card">
        <div class="card-image">
          <!--img src="imagenes\pruebaServicio\logo.png"-->
          <a href="{{ route('servicio.show',$service->idservicio) }}" class="btn-floating pulse halfway-fab waves-effect waves-light" style="background: #f12d2d;"><i class="material-icons">subdirectory_arrow_right</i></a>
        </div>
        <div class="card-content">
          <strong style="font-weight: bold" class="blue-text text-darken-4">{{ $service->nombre }}<strong>
          </div>
        </div>
      </div>
  @endforeach
  <!--div class="col s12 l10 offset-l1">
    <div class="slider">
      <ul class="slides">
        <li>
          <img class="green" src="" alt="">
          <div class="caption center-align">
            <h3>Salud</h3>
            <h5 class="light">En esta categoría encontrarás:
              Doctores, Clínicas, Hospitales, Farmacias y más</h5>
            <a class="btn waves-effect white green-text" href="{{ route('cat_salud') }}">Ir a Categoría Salud</a>
          </div>
        </li>
        <li>
          <img src="" alt="" class="orange accent-4">
          <div class="caption left-align">
            <h3>Comida</h3>
            <h5 class="light">En esta categoría encontrarás:
              Restaurantes, Cafeterías, Comedores y más</h5>
            <a class="btn waves-effect white orange-text text-accent-4" href="#">Ir a Categoría Comida</a>
          </div>
        </li>
        <li>
          <img src="" alt="" class="purple">
          <div class="caption right-align">
            <h3>Comercio</h3>
            <h5 class="light">En esta categoría encontrarás:
              Tiendas, Centros Comerciales, Ferreterías, Librerías y más</h5>
            <a class="btn waves-effect white purple-text" href="comercio.html">Ir a Categoría Comercio</a>
          </div>
        </li>
        <li>
          <img src="" alt="" class="red">
          <div class="caption left-align">
            <h3>Profesional</h3>
            <h5 class="light">En esta categoría encontrarás:
              Abogados, Ingenieros, Contadores, Administradores y más</h5>
            <a class="btn waves-effect white red-text" href="profesional.html">Ir a Categoría Profesional</a>
          </div>
        </li>
        <li>
          <img src="" alt="" class="amber">
          <div class="caption right-align">
            <h3>Ocio</h3>
            <h5 class="light">En esta categoría encontrarás:
              Centros de convivencia y diversos lugares para divertirte</h5>
            <a class="btn waves-effect white amber-text" href="ocio.html">Ir a Categoría Ocio</a>
          </div>
        </li>
      </ul>
    </div>
  </div-->
  {{$servicio->render()}}
</div>

@endsection

resources/views/plantilla.blade.php
<!DOCTYPE html>
<html lang="es">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-rc.2/css/materialize.min.css">
    <link rel="stylesheet" href="/css/styles.css">
    <title>Find Service Xela</title>
    <link rel="shortcut icon" href="/imagenes/l2.ico"/>
    @yield('head')
  </head>

  <body>
    <header>
      <!-- Barra de navegación responsive-->
      <div id="barra-nav" class="navbar-fixed">
        <nav>
          <div id="div_header" class="nav-wrapper container">
            <!-- Logo -->
            <a href="{{ route('home') }}" class="brand-logo"><img src="/imagenes/l2.png" alt="Logo" class="left hide-on-med-and-down" height="75px">Find Service</a>
            <!-- Icono de menu (responsive) -->
            <a href="#" data-target="menu-movil" id="menu_res" class="sidenav-trigger light"><i class="material-icons">menu</i></a>
            <!-- Opciones de la barra de navegacion normal -->
            <ul id="menu" class="right hide-on-med-and-down">
              <li><a href=" {{ route('blog') }}" id="nav_btn" class="waves-effect waves-light">Blog</a></li>
              <li>
                <a href="#" id="nav_categorias" class="dropdown-trigger btn-large waves-effect waves-red" data-target='cat_dropdown'>
                  <i class="large material-icons right">expand_more</i>Categorías
                </a>
              </li>
              <ul id='cat_dropdown' class='dropdown-content'>
                <li><a id="categoria" href="{{ route('categoria','1' ) }}">Salud</a></li>
                <li><a id="categoria" href="{{ route('categoria','2' ) }}">Comida</a></li>
                <li><a id="categoria" href="{{ route('categoria','3' ) }}">Comercio</a></li>
                <li><a id="categoria" href="{{ route('categoria','4' ) }}">Profesional</a></li>
                <li><a id="categoria" href="{{ route('categoria','5' ) }}">Ocio</a></li>
              </ul>
              @guest
                <a href="#" id="nav_login" class="dropdown-trigger btn-large waves-effect waves-red" data-target='nav_dropdown'>
                  <i class="large material-icons right">expand_more</i>Sesión
                </a>
                <ul id='nav_dropdown' class='dropdown-content'>
                  <li><a id="sesion_dropdown" href="{{ route('login') }}">Iniciar Sesión</a></li>
                  <li><a id="sesion_dropdown" href="{{ route('signup') }}">Crear Usuario</a></li>
                  <li><a id="sesion_dropdown" href="{{ route('servicio.create') }}">Registrar Servicio</a></li>
                </ul>
              @else
                <a href="#" id="nav_logout" class="center dropdown-trigger btn-large waves-effect waves-red" data-target='nav_dropdown'>
                  <i class="large material-icons right">expand_more</i>{{ Auth::user()->name }}
                </a>
                <ul id='nav_dropdown' class='dropdown-content'>
                  <li><a id="sesion_dropdown" href="{{ route('sservice') }}">Registrar Servicio</a></li>
                  <li><a id="sesion_dropdown" href="{{ route('login') }}">Ver Perfil</a></li>
                  <li>
                    <a id="sesion_dropdown" href="{{ route('perfil',Auth::user()->id) }}">Ver Perfil</a>
                  </li>
                  <li>
                    <a id="sesion_dropdown" href="{{ route('logout') }}"
                     onclick="event.preventDefault();
                                  document.getElementById('logout-form').submit();">
                     Cerrar Sesión
                     </a>
                   </li>
                </ul>
                <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                    @csrf
                </form>
              @endguest
            </ul>
          </div>
        </nav>
      </div>

      <!-- Opciones del menu lateral (responsive) -->
      <ul class="sidenav" id="menu-movil">
        <li> <br> </li>
        <li class="center">
          <span id="logo_menu">
            <a href="{{ route('home') }}"><img src="imagenes/l4.png" alt="Logo" height="100px"></a>
          </span>
        </li>

        <li> <hr> </li>

        @guest
          <a href="#" id="snav_login" class="center-align dropdown-trigger btn-large waves-effect waves-red" data-target='snav_dropdown'>
            <i class="large material-icons right">expand_more</i>Sesión
          </a>
          <ul id='snav_dropdown' class='dropdown-content'>
            <li><a id="sesion_dropdown" href="{{ route('login') }}">Iniciar Sesión</a></li>
            <li><a id="sesion_dropdown" href="{{ route('signup') }}">Crear Usuario</a></li>
            <li><a id="sesion_dropdown" href="{{ route('sservice') }}">Registrar Servicio</a></li>
          </ul>
        @else
          <li>
            <div class="user-view">
              <!--div class="background">
                <img src="imagenes/Comida.jpg">
              </div-->
              <a href="#"><img class="circle center" src="" alt="Foto" height="200px"></a>
              <a href="#"><span class="black-text name" style="font-size: large;">{{ Auth::user()->name }}</span></a>
              <a href="#"><span class="black-text name" style="font-size: medium;">{{ Auth::user()->email }}</span></a>
              <a href="#" id="snav_logout" class="dropdown-trigger btn waves-effect waves-red" data-target='snav_dropdown'>
                <i class="material-icons right">expand_more</i>{{ Auth::user()->nombre }} {{ Auth::user()->apellido }}

              </a>
              <ul id='snav_dropdown' class='dropdown-content'>
                <li><a id="sesion_dropdown" href="">Ver Perfil</a></li>
                <li>
                  <a id="sesion_dropdown" href="{{ route('logout') }}"
                    onclick="event.preventDefault();
                      document.getElementById('logout-form').submit();">
                    Cerrar Sesión
                  </a>
                </li>
              </ul>
            </div>
          </li>

          <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
              @csrf
          </form>
        @endguest

        <li><a href="#" id="snav_btn" class="waves-effect waves-light">Servicios</a></li>
        <li><a href="#" id="snav_btn" class="waves-effect waves-light">Historial</a></li>
        <li><a href="#" id="snav_btn" class="waves-effect waves-light">Blog</a></li>
      </ul>
    </header>


    <!-- Contenido principal de la pagina -->
    <br>

    @yield('busqueda')

    <br><br>

    @yield('contenido')


    <footer class="page-footer">
      <div class="container">
        <div class="row">
          <div class="col s6">
            <h5 class="white-text">Find Service</h5>
            <p class="grey-text text-lighten-4">Busca cualquier servicio, Aquí lo encontrarás!</p>
          </div>
        </div>
      </div>
      <div class="footer-copyright" >
        <div class="container white-text">
          2018 Esta página está inspirada en
          <a id="findoctor" class="btn" href="https://www.findoctor.com/" target="_blank">Findoctor.com ©</a>
        </div>
      </div>
    </footer>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-rc.2/js/materialize.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
    <script>
      document.addEventListener('DOMContentLoaded', function() {
        var elems = document.querySelectorAll('.sidenav');
        var instances = M.Sidenav.init(elems);
      });

      document.addEventListener('DOMContentLoaded', function() {
        var elems = document.querySelectorAll('.parallax');
        var instances = M.Parallax.init(elems);
      });

      document.addEventListener('DOMContentLoaded', function() {
        var elems = document.querySelectorAll('.slider');
        var instances = M.Slider.init(elems,{
          interval:5000
        });
      });

      document.addEventListener('DOMContentLoaded', function() {
        var elems = document.querySelectorAll('.dropdown-trigger');
        var instances = M.Dropdown.init(elems);
      });
    </script>
    @yield('scripts')
  </body>
</html>

resources/views/plantillaCategoria.blade.php
@extends ('plantilla')

@section ('busqueda')

    <!-- Contenido principal de la pagina -->
    <br><br>
    <div class="container">
      <div class="row">
        <section class="col s12 center">
          <h1 class = "z-depth-5 red section white-text">SALUD</h1>
        </section>
        <section class="col s8 offset-s2 center">
          <form>
            <div class="input-field">
              <input id="search_bar" type="search" required>
              <label class="" for="search_bar"><i class="material-icons left">search</i>Busca servicios como hospitales, restaurantes, tiendas, etc...</label>
              <i class="material-icons">close</i>
            </div>
          </form>
        </section>
      </div>
    </div>
@endsection

@section ('contenido')
    <div class="container">
      <div class="row">
        @foreach ($servicio as $service)
          <div class="col s6 m4 l3">
            <div class="card">
              <div class="card-image">
                <!--img src="imagenes\pruebaServicio\logo.png"-->
                <a href="{{ route('servicio.show',$service->idservicio) }}" class="btn-floating pulse halfway-fab waves-effect waves-light green"><i class="material-icons">subdirectory_arrow_right</i></a>
              </div>
              <div class="card-content">
                <strong style="font-weight: bold" class="blue-text text-darken-4">{{ $service->nombre }}<strong>
                </div>
              </div>
            </div>
        @endforeach
      </div>
    </div>
@endsection

@section ('scripts')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-rc.2/js/materialize.min.js"></script>
    <script>
      document.addEventListener('DOMContentLoaded', function() {
        var elems = document.querySelectorAll('.sidenav');
        var instances = M.Sidenav.init(elems);
      });
      document.addEventListener('DOMContentLoaded', function() {
        var elems = document.querySelectorAll('.parallax');
        var instances = M.Parallax.init(elems);
      });
      document.addEventListener('DOMContentLoaded', function() {
        var elems = document.querySelectorAll('.carousel');
        var instances = M.Carousel.init(elems);
      });
    </script>
    <script>
      var instance = M.Carousel.init({
        fullWidth: true,
        indicators: true
      });
    </script>
@endsection